### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by codingtmd** [RPGGO-AI/l-gos-spec#1]
Used for the schema discussion and Q&A

**Comment by jlulxy** [comment]
<img width="446" alt="image" src="https://github.com/user-attachments/assets/bdbad0f1-2c56-4fc5-a077-3d58d80a7d95">
这里是不是应该更名为 CharacterCard，整个项目没有Character的定义

**Comment by jlulxy** [comment]
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/e98d43aa-a470-41bb-9c39-20973382c049">

关于 entries的使用和 case 我没有看懂，是否可以更详细点？给出entries例子和映射到提示词的具体文字？

**Comment by jlulxy** [comment]
<img width="798" alt="image" src="https://github.com/user-attachments/assets/8d1d337f-50fc-434f-a3a2-01bfe0abba4a">

category的定义是不是写的位置不对 应该紧临category

**Comment by jlulxy** [comment]
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/65e90095-06f6-4833-b9a6-a78e54d83653">

这里感觉比较难理解，status_id和status_threshold是一一对应的？ status 是否可以给一个明晰的例子哇？
                    "status_id": ["sanity", "health", "Thompson's sanity", "Thompson's health"],
                    "status_threshold": [0, 0, 0, 0],
   这里的数据结果如果是这样的：
   "status":[
    {
        "property": "sanity",
        "status": 0
    },
]

**Comment by AlexFeYang** [comment]
CharacterCard和Cover_url的问题已经校正。 @jlulxy 
 @pptbtRpggo 看看goal的问题

**Comment by AlexFeYang** [comment]
Entries我稍微修饰了一些例子，需要进一步澄清的话可以约着讨论一下，这里keys的结构和平台不同，因为预设了其他用途 @jlulxy

**Comment by pptbtRpggo** [comment]
> <img alt="image" width="1098" src="https://private-user-images.githubusercontent.com/18388175/392680463-65e90095-06f6-4833-b9a6-a78e54d83653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTAzMTEsIm5iZiI6MTczNDA5MDAxMSwicGF0aCI6Ii8xODM4ODE3NS8zOTI2ODA0NjMtNjVlOTAwOTUtMDZmNi00ODMzLWI5YTYtYTc4ZTU0ZDgzNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDExNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDU5OWY0NDA3MjhjNTY3MWQyMWI3YmIwYzhhNWVlMjdhODEwNDU4MWM1OGJjMzI4Zjc1YjViMjY3MDViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hfpk_hohBhKKAT7zP3h_FlMG_u-tQ3C8jLcsjAgahDQ">
> 这里感觉比较难理解，status_id和status_threshold是一一对应的？ 这里的数据结果如果是这样的：会不会好一些？ "status":[ { "property": "status1", "status": 0 }, { "property": "status2", "status": 0 } ]

这部分已修改

**Comment by codingtmd** [comment]
> Entries我稍微修饰了一些例子，需要进一步澄清的话可以约着讨论一下，这里keys的结构和平台不同，因为初衷预设了其他用途。 第一版也可以剪枝一下， 还原平台的用法？现在key在l-gos中是格式为list，可以改为str，单纯只作为title使用 @codingtmd @jlulxy

Keys比较好，这样大家知道是用来检索用的
